{% set name = "elecsolver" %}
{% set version = "1.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/williampiat3/ElecSolver/archive/refs/tags/{{ version }}.tar.gz
  sha256: 811a68126f595c63832582fbb3d3bf3c5b1932a254f7450fb3911d433cfc7e7b

build:
  number: 0
  noarch: python
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=60
    - setuptools-scm >=8.0
    - pip
  run:
    - python >={{ python_min }},<=3.12
    - numpy
    - networkx
    - scipy

test:
  requires:
    - python {{ python_min }}
    - python-mumps
    - pytest
  imports:
    - ElecSolver
  source_files:
    - tests
  commands:
    - python -m pytest tests

about:
  home: https://github.com/williampiat3/ElecSolver
  summary: Electric system formulation in Python
  license_family: MIT
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - williampiat3
