schema_version: 1

context:
  name: elecsolver
  version: 2.0.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/williampiat3/ElecSolver/archive/refs/tags/${{ version }}.tar.gz
  sha256: ca5d2a6a240f3cccbc2feab26388665c78ee14f6ae3471e5b4f73496402b7a11



build:
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  number: 0

requirements:
  host:
    - setuptools >=60
    - setuptools-scm >=8.0
    - pip
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}
    - numpy
    - networkx
    - scipy

tests:
  - python:
      imports:
        - ElecSolver
  - script:
      - python -m pytest tests
    requirements:
      run:
        - python ${{ python_min }}.*
        - python-mumps
        - pytest
    files:
      source:
        - tests

about:
  homepage: https://github.com/williampiat3/ElecSolver
  summary: Electric system formulation in Python
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - williampiat3
    - Pimss
