schema_version: 1

context:
  name: elecsolver
  version: 2.1.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/williampiat3/ElecSolver/archive/refs/tags/${{ version }}.tar.gz
  sha256: ba0c03e96f642086cc1780f3deb4a932df2ba8c7f4c4e148781818da3ff4fc06



build:
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  number: 0

requirements:
  host:
    - setuptools >=60
    - setuptools-scm >=8.0
    - pip
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}
    - numpy
    - networkx
    - scipy

tests:
  - python:
      imports:
        - ElecSolver
  - script:
      - python -m pytest tests
    requirements:
      run:
        - python ${{ python_min }}.*
        - python-mumps
        - pytest
    files:
      source:
        - tests

about:
  homepage: https://github.com/williampiat3/ElecSolver
  summary: Electric system formulation in Python
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - williampiat3
    - Pimss
